base-env.PATH = '/usr/bin:/bin:/sbin'

[debug]
open-bar = true
var.debug = 'number:0-1'
env.CFLAGS = '-DDEBUG={debug}'
commands = [ 'env', 'setpriv -d' ]

[set-dns]
src-groups = [ 'punks' ]
var.server-ip = 'ip-addr'
commands = [ 'echo nameserver {server-ip} > /etc/resolv.conf' ]
